### ISSUE TITLE
非要用到gpt-4吗？

### ISSUE THREAD

**Issue by DinoLiww** [OpenBMB/AgentVerse#21]
这个项目非要用到gpt-4吗？
如果只是3.5就不能运行？哪里可以改动成3.5可以走下去？

**Comment by chenweize1998** [comment]
`config.yaml`:
```yaml
agents:
   - agent_type: ...
      ...
      llm:
        llm_type: gpt-3.5-turbo
        model: gpt-3.5-turbo (or gpt-3.5-turbo-16k, gpt-3.5-turbo-0301, ...)
        temperature: 0.7
        max_tokens: 250
```
